//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStock
    {
        public int stockID { get; set; }
        public int bookID_fk { get; set; }
        public int availableQty { get; set; }
        public System.DateTime updatedDate { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
    }
}
