//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBookDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderBookDetail()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int ordBookDetailsID { get; set; }
        public int ordID_fk { get; set; }
        public int bookID_fk { get; set; }
        public int quantity { get; set; }
        public double totalPrice { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
