//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payID { get; set; }
        public int ordID_fk { get; set; }
        public double amount { get; set; }
        public System.DateTime dateOfPay { get; set; }
        public int payMethodID_fk { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
