//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public int returnID { get; set; }
        public int requestID_fk { get; set; }
        public System.DateTime returnDate { get; set; }
        public double refundAmount { get; set; }
        public string status { get; set; }
    
        public virtual ReturnRequest ReturnRequest { get; set; }
    }
}
