//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBooksWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int reviewID { get; set; }
        public int ordBookDetailsID_fk { get; set; }
        public string comments { get; set; }
        public double rating { get; set; }
        public System.DateTime dateOfReview { get; set; }
    
        public virtual OrderBookDetail OrderBookDetail { get; set; }
    }
}
